name: kroscek
description: "Crop Inspection and Check Result"
publish_to: 'none'

version: 1.10.6+2

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.1
  package_info_plus: ^8.0.0
  convex_bottom_bar: ^3.0.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.0.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  firebase_storage: ^12.1.3
  file_picker: ^8.0.7
  excel: ^4.0.3
  path_provider: ^2.0.11
  firebase_app_check: ^0.3.0+4
  googleapis: ^11.4.0
  googleapis_auth: ^1.1.0
  url_launcher_android: ^6.3.9
  url_launcher: ^6.3.0
  flutter_custom_tabs: ^2.1.0
  webview_flutter: ^4.8.0
  gsheets: ^0.5.0
  shimmer: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^3.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  animated_text_kit: ^4.2.2
  dropdown_search: ^6.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.13
  connectivity_plus: ^6.0.5
  syncfusion_flutter_datagrid: ^27.1.52
  google_maps_flutter: ^2.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.png
    - assets/login_background.png
    - assets/google_logo.svg
    - assets/credentials.json
    - assets/loading.json
    - assets/vegetative.png
    - assets/generative.png
    - assets/preharvest.png
    - assets/harvest.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"